// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "DDREnemyTypes.h"
#include "NativeGameplayTags.h"

namespace DDRTags
{
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Light);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Launcher);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Air);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_AirSlam);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Melee_Slash);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Ranged_Bolt);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Elite_Smash);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Elite_Shove);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss_Charge);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss_AoE);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss_Combo);

	/** IDs de catálogo (doc 51) — um por UDDREnemyData::EnemyId. */
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Grunt_Melee);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ranged_Archer);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Elite_Brute);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Boss_Guardian);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Attacking);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Stagger);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_InAir);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Airborne);
	/** Queda do slam / combate aéreo — AnimBP usa Jump_Combat_Loop/End. */
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_SlamFall);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Boss_Vulnerable);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Sprinting);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Dashing);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Dash);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Launcher);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Enemy);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Boss);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Boss_NoLaunch);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Hit);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Launch);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_SlamLand);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_PoiseBreak);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_PoiseDamage);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Hit_Light);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Enemy_Telegraph);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Proj_Telegraph);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Proj_Impact);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Launch);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Slam);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Death_Enemy);

	/** EnemyId default por Role quando o DataAsset nao preenche EnemyId (doc 51). */
	DARKDUNGEONRIFT_API FGameplayTag GetDefaultEnemyIdForRole(EDDREnemyRole Role);
}
