// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace DDRTags
{
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Light);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Attacking);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Sprinting);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Dashing);
	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Dash);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Enemy);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Hit);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);

	DARKDUNGEONRIFT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Hit_Light);
}
